services:

  server:
    build:
      dockerfile: ./dev_env/nginx/docker/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./dev_env/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/html/vendor
      - ./app:/var/www/html

  mariadb:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=app
    ports:
      - '3306:3306'

  app:
    build:
      dockerfile: ./dev_env/php/docker/Dockerfile
    volumes:
      - ./dev_env/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html
    command: sh -c "composer install && php-fpm"
    depends_on:
      - mariadb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: