services:

  mariadb:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=app
    ports:
      - '3306:3306'

  app:
    build:
      dockerfile: ./dev_env/php/docker/Dockerfile
    volumes:
      - ./dev_env/php/conf/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html
    depends_on:
      - mariadb
    ports:
      - 8080:80

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: