services:
  server:
    build:
      dockerfile: ./env/nginx/docker/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./env/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - app
    networks:
      - app-network

  mariadb:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=app
    ports:
      - '3306:3306'
    networks:
      - app-network

  app:
    build:
      dockerfile: ./env/php/docker/Dockerfile
    volumes:
      - ./env/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html
    command: sh -c "composer install && php-fpm"
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge